#!/usr/bin/env python
import sys
import random
import argparse
import csv

##### Argument Parser #####
descr_str = 'The nifty little command line "Rock-Paper-Scissors" program'
parser = argparse.ArgumentParser(description = descr_str)
parser.add_argument("throw", choices=['r','p','s'],
                    help="throw your hand")
args = parser.parse_args()


##### Lists and Dictionaries #####
throws = ["Rock", "Paper", "Scissors"]
symbols = ['r', 'p', 's']
name = dict(zip(symbols, throws))
relations = (('r','s'), ('p','r'), ('s','p'))
doodles = {}


##### CSV Doodles #####
with open('/Users/lucasstinchcombe/Documents/Python/rockpaperscissors/doodles.csv', 'rb') as csvfile:
    reader = csv.reader(csvfile)
    for line in reader:
        key = line.pop(0)
        doodles[key] = line


#######################################
################ MAIN #################

def main():
    # Player and Computer throw and result
    player = args.throw
    computer = random.choice('rps')
    result(player, computer)

# def result(x, y):
#     j = tuple([name[i] for i in (x,y)])
#     if (x, y) in relations:
#         print "\t%s beats %s \t You Win" % j
#     elif x != y:
#         print "\t%s beats %s \t You Lose" % j[::-1]
#     else:
#         print "\t%s vs. %s \t Its a Tie" % j

def result(x, y):
    if (x, y) in relations:
        (k1,k2,k,s) = (x.upper(),y,'>>','win')
    elif x != y:
        (k1,k2,k,s) = (x,y.upper(),'<<','lose')
    else:
        (k1,k2,k,s) = (x,x,'==', 'tie')
    print_doodle(s)
    visual_result(k1,k2,k)

def visual_result(k1,k2,k):
    for i in range(len(doodles[k1])):
        print doodles[k1][i],
        print doodles[k][i],
        print doodles[k2][i]



def print_doodle(key):
    for x in doodles[key]:
        print x

if __name__ == "__main__":
    main()
