#!/usr/bin/env python
import os
import sys
import argparse
import random
import csv
import time

##### Argument Parser #####
descr_str = 'The nifty little command line "Rock-Paper-Scissors" program'
parser = argparse.ArgumentParser(description = descr_str)
args = parser.parse_args()

##### Lists and Dictionaries #####
throws = ["Rock", "Paper", "Scissors"]
symbols = ['r', 'p', 's']
name = dict(zip(symbols, throws))
relations = (('r','s'), ('p','r'), ('s','p'))
doodles = {}

##### CSV #####
CSV = os.path.dirname(sys.argv[0]) + '/csv/'
with open(CSV+'RPSdoodles.csv', 'rb') as csvfile:
    reader = csv.reader(csvfile)
    for line in reader:
        key = line.pop(0)
        doodles[key] = line

##### Classes #####
class Player:
    def __init__(self):
        self.Rounds = []

    def Round_Info(self,i):
        div = "-"*15
        info = div + "\nROUND "+ repr(i) + "\n" + div
        return info

#######################################
################ MAIN #################

def main():

    #initialize Player YOU
    You = Player()
    div = "-"*15
    # Player and Computer throw and result
    for i in range(3):
        print You.Round_Info(i+1)
        You.Rounds.append(showdown())
        while You.Rounds[i]=='tie':
            You.Rounds[i] = showdown()
    print You.Rounds

def showdown():
    for i in throws:
        time.sleep(0.5)
        print '\t' + i + ' ->',
        sys.stdout.flush()
    player = raw_input()
    computer = random.choice('rps')
    return result(player, computer)

def result(x, y):
    if (x, y) in relations:
        (k1,k2,k,s) = (x.upper(),y,'>>','win')
    elif x != y:
        (k1,k2,k,s) = (x,y.upper(),'<<','lose')
    else:
        (k1,k2,k,s) = (x,x,'==', 'tie')
    print_tags()
    visual_result(k1,k2,k)
    return s

def visual_result(k1,k2,k):
    for i in range(len(doodles[k1])):
        print doodles[k1][i],
        print doodles[k][i],
        print doodles[k2][i]

def print_doodle(key):
    for x in doodles[key]:
        print x

def print_tags():
    print '\n\n'+' '*9 + 'YOU' + ' '*9,
    print ' '*17,
    print ' '*6 + 'COMPUTER' + ' '*7

if __name__ == "__main__":
    main()
